In [2]:
import numpy as np

In [3]:
x = np.arange(9).reshape((3,3))

In [4]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.diag(x)

array([0, 4, 8])

In [6]:
np.diag(x, k=1)

array([1, 5])

In [7]:
np.diag(x, k=-1)

array([3, 7])

In [8]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])